project:
  type: website
  output-dir: docs
  pre-render:  # This can be deleted if you are using the manually curated list of publications in publications.qmd
    - python xlsx_to_yml.py  # Automatically generate publications.yml from publications.xlsx
    
# Meta
description-meta: "Academic Website of Thanh Lam Nguyen"
author-meta: "Thanh Lam Nguyen"

website:
  title: "Thanh Lam Nguyen"
  image: "files/images/avatar.jpeg"
  description: "Academic Website of Thanh Lam Nguyen"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu:
          - text: Publications Listing  # Automatically generated from publications.xlsx
            href: pub-listing.qmd
          - text: Publications  # Manually curated list of publications
            href: publications.qmd            
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Grants
            href: projects.qmd                                
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      #- text: Outreach
        #menu:        
        #- text: Presentations
          #href: posts.qmd#category=presentation                   
      #- text: Group   # Comment the Group part out to remove the Group page
        #href: people.qmd

    right: 
      - text: CV
      #  href: files/profiles/CV.pdf
      - icon: github
        href: https://github.com/nguyen-thanhlam
        target: _blank
     # - text: "{{< fa brands bluesky >}}"
     #   href: https://bsky.app
     #   target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "Thanh Lam Nguyen(http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built with [Quarto](https://quarto.org)"
    right:  
      - icon: github
        href: https://github.com/nguyen-thanhlam
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  # draft-mode: unlinked
  
  open-graph: true
  
  twitter-card: true 
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"

